import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AddToCart } from "@/components/add-to-cart";
import { Button } from "@/components/button";
import { PriceDisplay } from "@/components/price-display";
import { ProductImageGallery } from "@/components/product-image-gallery";
import { getProductBySlug } from "@/lib/products/service";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const product = await getProductBySlug((await params).slug); return { title: product?.title ?? "Product", description: product?.description }; }
export default async function ProductPage({ params }: Props) { const product = await getProductBySlug((await params).slug); if (!product) notFound(); const discount = product.compareAtPrice ? Math.round((1 - product.price / product.compareAtPrice) * 100) : 0; return <main className="product-detail container"><nav className="breadcrumbs sans" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={`/category/${product.categorySlug ?? product.category.toLowerCase()}`}>{product.category}</Link><span>/</span><span>{product.title}</span></nav><ProductImageGallery images={product.images} title={product.title} /><section className="product-info"><p className="eyebrow">{product.category}</p><h1>{product.title}</h1>{product.rating ? <p className="rating sans"><span>★ {product.rating}</span> <small>{product.reviewCount} reviews</small></p> : null}<PriceDisplay price={product.price} compareAtPrice={product.compareAtPrice} />{discount > 0 ? <span className="detail-discount sans">{discount}% off</span> : null}<p className="detail-description sans">{product.description}</p><dl className="product-specs sans">{Object.entries(product.attributes).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}<div><dt>Availability</dt><dd>{product.availability === "IN_STOCK" ? "In stock" : "Currently unavailable"}</dd></div></dl><div className="delivery-box sans"><strong>Check delivery</strong><p>Enter your pincode to check delivery availability.</p><form><input aria-label="Pincode" inputMode="numeric" placeholder="Enter pincode" /><button type="button">Check</button></form></div><AddToCart product={product} /><Button href="/cart" variant="quiet">Buy now</Button></section></main>; }